# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nasc', models.DateTimeField(verbose_name='Data de nascimento')),
            ],
        ),
    ]
