# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_auto_20170824_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='Cidade')),
                ('macro_number', models.CharField(max_length=200, verbose_name='Nº Macro')),
                ('macro_read', models.CharField(max_length=200, verbose_name='Leitura')),
                ('pontual_macro', models.CharField(max_length=200, verbose_name='Q = Pontual Macro')),
                ('pontual_ultrasonico', models.CharField(max_length=200, verbose_name='Q = Pontual Ultrasonico')),
                ('dn', models.CharField(max_length=200, verbose_name='DN')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('entry_date', models.DateTimeField(verbose_name='Data de Entrada')),
                ('observation', models.CharField(max_length=200, verbose_name='Observação')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa', verbose_name='Pessoa')),
            ],
        ),
    ]
