# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_prontuario_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuario',
            name='data_cadastro',
        ),
    ]
