# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_remove_prontuario_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='data_cadastro',
            field=models.DateTimeField(default='04/10/2017', verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
    ]
